stages:
    - build_dev
    - build    

builddev-job:
  stage: build_dev
  tags:
    - ulb-ojs-dev

  script:
    - echo "Install OJS DEVELOP"
    - ./build.sh $SMTP_PASS dev
    - ./stop-ojs dev
    - if [ $(curl -LI https://publicdev.bibliothek.uni-halle.de/ -o /dev/null -w '%{http_code}\n' -s) != "200" ]; then exit 1; fi

build-job:
  stage: build

  needs:
    - builddev-job

  tags:
    - ulb-ojs

  script:
    - echo "Install OJS PRODUCTION"
    - ./build.sh $SMTP_PASS prod
