stages:
    - build_dev
    - build    

variables:
    GIT_SUBMODULE_STRATEGY: recursive

builddev-job:
  stage: build_dev
  tags:
    - ulb-ojs-dev

  script:
    - echo "Install OJS DEVELOP"
    - ./build.sh $SMTP_PASS dev
    - ./stop-ojs dev
    - ./start-ojs dev
    - sleep 10
    - >
      if [ $(curl -LIk https://publicdev.bibliothek.uni-halle.de/ -o /dev/null -w '%{http_code}\n' -s) != "200" ]; then
        echo Development Server fails!
        exit 1;
      else
        echo Development Server started successfully!;
        echo We now restart Production Server;
      fi

build-job:
  stage: build

  needs:
    - builddev-job

  tags:
    - ulb-ojs

  script:
    - echo "Install OJS PRODUCTION"
    - ./build.sh $SMTP_PASS prod
