# File: docker-compose.yml
# Access via "http://localhost:8080"
#
# Call example:
# $ docker-compose -f docker-compose-ulb.yml up

version: "3.6"

networks:
  inside:
    external: false

services:
  db:
    image: mariadb:10.2
    env_file:
      - .env
    container_name: "ojsdev_db_ulb"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /data/ojsdev/db:/var/lib/mysql
      - /data/ojsdev/logs/db:/var/log/mysql
      - ./resources/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
#      - ./config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
#      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  ojsdev:
    # image: pkpofficial/ojs:${OJS_VERSION_ULB_DEV}
    build: .
    image: ojs:${OJS_VERSION_ULB_DEV}
    env_file:
      - .env
    container_name: "ojsdev_app_ulb"
    hostname: "${COMPOSE_PROJECT_NAME}"
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/ojsdev/private:/var/www/files
      - /data/ojsdev/public:/var/www/html/public
      - /data/ojsdev/logs/app:/var/log/apache2
      - /data/ojsdev/config/ojs.config.inc.php:/var/www/html/config.inc.php:ro
      - /data/ojsdev/config/php.ulb.ini:/etc/php7/conf.d/php.ulb.ini:ro
      - /data/ojsdev/config/ojsdev.conf:/etc/apache2/conf.d/ojs.conf:ro
      # ULB custom made plugins
      - /data/ojsdev/plugins/ulb_theme:/var/www/html/plugins/themes/ulb_theme
      - /data/ojsdev/plugins/searchMark:/var/www/html/plugins/generic/searchMark
      # - /data/ojsdev/config/favicon.ico:/var/www/html/favicon.ico

#      # WARNING: You can only enable file-volumes if file exists in the container.
#      - ./config/apache.htaccess:/var/www/html/.htaccess
#      - ./php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
