#!/bin/bash

if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ] && [ $1 != "local" ])
    then
        echo "Parameter 'dev' oder 'prod' oder 'local' fehlt"
        exit 0

elif [ "$1" == "dev" ] ||  [ "$1" == "local" ]
    then
        echo "start docker-compose with docker-compose-ojs$1.yml"
        docker-compose -f docker-compose-ojs"$1".yml -p "$1" up -d

elif [ $1 == "prod" ]
    then
        echo "start docker-compose with docker-compose-ojs$1.yml"
        docker-compose -f docker-compose-ojsprod.yml -p "$1" up -d
fi
