#!/bin/bash

if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ])
    then
        echo "Parameter 'dev' oder 'prod' fehlt"
        exit 0

elif [ $1 == "dev" ]
    then
        docker-compose -f docker-compose-ojsdev.yml -p $1 down

elif [ $1 == "prod" ]
    then
        echo stop docker compose
        docker-compose -f docker-compose-ojsprod.yml -p $1 down
fi

